services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Ejecuta el script de inicialización

  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy  # Espera a que MySQL esté listo antes de iniciar
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=nest
      - DB_PASSWORD=app
      - DB_NAME=degree_work_db

networks:
  app-network:  # Definir la red para la comunicación entre los contenedores
    driver: bridge